---

language: node_js

node_js:
  - lts/*

sudo: required

services:
  - docker

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-5-dev

install:
  - cd ~/ && npm install elementary/houston#v2-build-fix
  - cd ~/node_modules/@elementaryos/houston && npm ci
  - cd ~/node_modules/@elementaryos/houston && npm run build

script:
  - ~/node_modules/@elementaryos/houston/dest/bin.js ci
    --type system-app
    --name-appstream io.elementary.code.desktop
    --name-domain io.elementary.code
    --name-human Code
