---

language: node_js

node_js:
  - lts/*

sudo: required

services:
  - docker

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-5-devo

install:
  - npm install elementary/houston#v2-build-fix

script:
  - houston ci
    --type system-app
    --name-appstream io.elementary.code.desktop
    --name-domain io.elementary.code
    --name-human Code
